#!/bin/bash

# Check if the correct number of arguments is passed
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <ip> <port> <time>"
    exit 1
fi

# Assign parameters to variables
IP=$1
PORT=$2
TIME=$3

# Run each file with the parameters
# <./file_name> "$IP" "$PORT" "$TIME" "100"
./vb "$IP" "$PORT" "$TIME" "100"
./v0 "$IP" "$PORT" "$TIME" "100"
./v1 "$IP" "$PORT" "$TIME" "100"
./v2 "$IP" "$PORT" "$TIME" "100"
./v3 "$IP" "$PORT" "$TIME" "100"
./v4 "$IP" "$PORT" "$TIME" "100"
./v5.1 "$IP" "$PORT" "$TIME" "100"
./v5.2 "$IP" "$PORT" "$TIME" "100"
./soul "$IP" "$PORT" "$TIME" "100"
./bgmi-soul "$IP" "$PORT" "$TIME" "100"
