#!/bin/bash

# Check if the correct number of arguments is passed
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <ip> <port> <time>"
    exit 1
fi

# Assign parameters to variables
IP=$1
PORT=$2
TIME=$3

# Run each file with the parameters
# <./file_name> "$IP" "$PORT" "$TIME" "100"

